def get() -> str:
    return """ArreteId,Numéro,CodeZA,Particulier,Entreprise,Collectivite,Exploitation,Eau_Potable,Niveau,Thematique,Nom_Usage,Nom_Usage_Personalise,Precision,Heure_Debut,Heure_Fin
123,2022-04,28_14_0103,OUI,OUI,OUI,OUI,NON,Interdiction,ICPE,Usage ICPE non soumis à un APC relatif à la sécheresse,Installations Classées Pour l'Environnement (ICPE),Les usages peuvent être interdits.,,
234,2022-04,28_14_0103,OUI,OUI,OUI,OUI,NON,Réduction de prélèvement,ICPE,Usage ICPE non soumis à un APC relatif à la sécheresse,Installations Classées Pour l'Environnement (ICPE),"Les prélèvements peuvent être limités aux strictes nécessités des processus industriels.  Report des opérations exceptionnelles, essais ou modifications de procédés générateurs d’une surconsommation en eau ou générateurs d’eaux polluées non strictement néc (...)",,
345,2022-04,28_14_0103,OUI,OUI,OUI,OUI,NON,Réduction de prélèvement,ICPE,Usage ICPE non soumis à un APC relatif à la sécheresse,Installations Classées Pour l'Environnement (ICPE),"L’arrosage des pelouses, des espaces verts de l’établissement ainsi que du lavage des voies de circulation et aires de stationnement de l’établissement, sauf pour des raisons de sécurité ou d’hygiène dûment justifiées, peut être réglementé.  Les essais pér (...)",,
456,2022-04,28_14_0103,OUI,OUI,OUI,OUI,NON,Sensibilisation,ICPE,Usage ICPE non soumis à un APC relatif à la sécheresse,Installations Classées Pour l'Environnement (ICPE),"Il est fait appel à la responsabilité et au sens civique de tous les usagers (particuliers, collectivités, entreprises, agriculteurs) pour faire un usage raisonné et économe de l’eau en suivant scrupuleusement les recommandations d’usage suivantes :  - évi (...)",,
567,2022-04,28_14_0103,OUI,OUI,OUI,OUI,NON,Interdiction sauf exception,Arrosage,Arrosage des terrains de sport,"Arrosage des stades, des terrains de golf","Interdit pour les golfs  Exception :  Sous condition pour les golfs qui respectent la charte nationale « golf et environnement »  : Interdiction d’arroser les golfs à l’exception des greens qui pourront toutefois être préservés, sauf en cas de pénurie d’ea (...)",,
678,2022-04,28_14_0103,OUI,OUI,OUI,OUI,NON,Interdiction sauf exception,Arrosage,Arrosage des terrains de sport,"Arrosage des stades, des terrains de golf", Interdit pour les golfs  Exception :  Sous condition pour les golfs qui respectent la charte nationale « golf et environnement »  : Réduction des volumes d’au moins 60 % par une interdiction d’arroser les fairways 7j/7. Interdiction d’arroser les terrains (...),,
789,2022-04,28_14_0103,OUI,OUI,OUI,OUI,NON,Sensibilisation,Arrosage,Arrosage des terrains de sport,"Arrosage des stades, des terrains de golf","Il est fait appel à la responsabilité et au sens civique de tous les usagers (particuliers, collectivités, entreprises, agriculteurs) pour faire un usage raisonné et économe de l’eau en suivant scrupuleusement les recommandations d’usage suivantes :  - évi (...)",,
321,2022-04,28_14_0103,OUI,OUI,OUI,OUI,NON,Interdiction sauf exception,Arrosage,Arrosage des terrains de sport,"Arrosage des stades, des terrains de golf",Interdit pour les golfs  Exception :  Sous condition pour les golfs qui respectent la charte nationale « golf et environnement »  : Interdiction d’arroser les terrains de golf de 8 heures à 20 heures de façon à diminuer la consommation d’eau sur le volume  (...),,
432,2022-04,28_14_0103,OUI,OUI,OUI,OUI,NON,Interdiction sauf exception,Arrosage,Arrosage des terrains de sport,Arrosage des stades et des pistes hippiques ,"L’arrosage des stades et des pistes hippiques peut être interdit. Une dérogation pourra être demandée au préfet pour l’arrosage des pistes hippiques non engazonnées, des aires de sport en terre battue et des greens.",,
543,2022-04,28_14_0103,OUI,OUI,OUI,OUI,NON,Réduction de prélèvement,Arrosage,Arrosage des terrains de sport,Arrosage des stades et des pistes hippiques ,L’arrosage des stades et des pistes hippiques peut être interdit en journée et limité à 2 nuits par semaine. Une dérogation pourra être demandée au préfet pour la réutilisation des eaux usées et pour l’arrosage des pistes hippiques non engazonnées et des a (...),,
654,2022-04,28_14_0103,OUI,OUI,OUI,OUI,NON,Réduction de prélèvement,Arrosage,Arrosage des terrains de sport,Arrosage des stades et des pistes hippiques ,L’arrosage des stades et des pistes hippiques peut être interdit en journée. Une dérogation pourra être demandée au préfet pour l’arrosage des pistes hippiques non engazonnées et des aires de sport en terre battue.,,
765,2022-04,28_14_0103,OUI,OUI,OUI,OUI,NON,Sensibilisation,Arrosage,Arrosage des terrains de sport,Arrosage des stades et des pistes hippiques ,"Il est fait appel à la responsabilité et au sens civique de tous les usagers (particuliers, collectivités, entreprises, agriculteurs) pour faire un usage raisonné et économe de l’eau en suivant scrupuleusement les recommandations d’usage suivantes :  - évi (...)",,
765,2022-04,28_14_0103,OUI,OUI,OUI,OUI,NON,Interdiction,Arrosage,Arrosage des jardins potagers,Arrosage des potagers,L’irrigation des potagers peut être interdite.,,
765,2022-04,28_14_0103,OUI,OUI,OUI,OUI,NON,Réduction de prélèvement,Arrosage,Arrosage des jardins potagers,Arrosage des potagers,L’irrigation des potagers peut être réglementée.,,"""
