def get_mocked_restrictions():
    return [
        ('alerte renforcée', 'Interdiction', 'Alimentation des fontaines publiques et privées', 'Alimentation des fontaines publiques et privées d’ornement', '', ' Interdit', None, None),
        ('alerte renforcée', 'Interdiction', 'Alimentation des fontaines publiques et privées', 'Alimentation des fontaines publiques et privées d’ornement', '', " qui ne fonctionnent pas sur un circuit d'eau fermé", None, None),
        ('alerte renforcée', 'Interdiction', 'Alimentation des fontaines publiques et privées', 'Alimentation des fontaines publiques et privées d’ornement', '', "qui ne fonctionnent pas sur un circuit d'eau fermé", None, None),
        ('alerte renforcée', 'Interdiction', 'Arrosage', 'Arrosage des espaces verts', '', ' Interdit', None, None),
        ('alerte renforcée', 'Interdiction', 'Arrosage', "Arrosage des golfs(Conformément à l'accord cadre golf et environnement 2019-2024", '', ' Interdit', None, None),
        ('alerte renforcée', 'Interdiction', 'Arrosage', 'Arrosage des jardins potagers', '', ' Interdit', None, None),
        ('alerte renforcée', 'Interdiction', 'Arrosage', 'Arrosage des pelouses, massifs fleuris', '', ' hors arrosage par micro-irrigation et goutte à goutte', None, None),
        ('alerte renforcée', 'Interdiction', 'Arrosage', 'Arrosage des pelouses, massifs fleuris', '', ' Interdit', None, None),
        ('alerte renforcée', 'Interdiction sauf exception', 'Arrosage', "Arrosage des golfs(Conformément à l'accord cadre golf et environnement 2019-2024", '', "A l'exception des greens et des départs", None, None),
        ('alerte renforcée', 'Interdiction sauf exception', 'Arrosage', 'Arrosage des jardins potagers', '', 'les béals qui alimentent les jardins potagers sont soumis aux mêmes restrictions que les usages agricoles', None, None),
        ('alerte renforcée', 'Interdiction sauf exception', 'Nettoyage', 'Lavage de véhicules chez les particuliers', '', ' Sauf pour les véhicules ayant une obligation réglementaire (véhicule sanitaire ou alimentaire) ou technique (épareuse, bétonnière,...) et pour les organismes liés à la sécurité.', None, None),
        ('alerte renforcée', 'Interdiction sauf exception', 'Nettoyage', 'Lavage de véhicules chez les particuliers', '', 'Sauf pour les véhicules ayant une obligation réglementaire (véhicule sanitaire ou alimentaire) ou technique (épareuse, bétonnière, ...) et pour les organismes liés à la sécurité.', None, None),
        ('alerte renforcée', 'Interdiction sauf exception', 'Remplissage vidange', "Remplissage et vidange de piscines privées (de plus d'1 m3)", '', "A l'exception de la première mise en eau des piscines nouvellement construites. A l'exception de la mise à niveau.", None, None),
        ('alerte renforcée', 'Interdiction sauf exception', 'Remplissage vidange', "Remplissage et vidange de piscines privées (de plus d'1 m3)", '', 'Sauf la mise à niveau.', None, None),
        ('alerte renforcée', 'Interdiction sauf exception', 'Travaux en cours d’eau', 'Travaux en cours d’eau', '', "Sauf autorisation service Police de l'Eau.", None, None),
        ('alerte renforcée', 'Interdiction sur plage horaire', 'Arrosage', 'Arrosage des espaces verts', '', 'NULL', 8, 20),
        ('alerte renforcée', 'Interdiction sur plage horaire', 'Arrosage', "Arrosage des golfs(Conformément à l'accord cadre golf et environnement 2019-2024", '', 'NULL', 8, 20),
        ('alerte renforcée', 'Interdiction sur plage horaire', 'Arrosage', 'Arrosage des jardins potagers', '', 'NULL', 8, 10),
        ('alerte renforcée', 'Interdiction sur plage horaire', 'Arrosage', 'Arrosage des jardins potagers', '', 'NULL', 10, 18),
        ('alerte renforcée', 'Interdiction sur plage horaire', 'Arrosage', 'Arrosage des pelouses, massifs fleuris', '', 'NULL', 8, 20),
        ('alerte renforcée', 'Pas de restriction', 'Abreuvement', 'Abreuvement des animaux', '', 'NULL', None, None),
        ('alerte renforcée', 'Sensibilisation', 'Alimentation des fontaines publiques et privées', 'Alimentation des fontaines publiques et privées d’ornement', '', 'Limitation volontaire', None, None),
        ('alerte renforcée', 'Sensibilisation', 'Arrosage', 'Arrosage des espaces verts', '', 'Limitation volontaire ', None, None),
        ('alerte renforcée', 'Sensibilisation', 'Arrosage', "Arrosage des golfs(Conformément à l'accord cadre golf et environnement 2019-2024", '', ' Limitation volontaire', None, None),
        ('alerte renforcée', 'Sensibilisation', 'Arrosage', 'Arrosage des jardins potagers', '', ' Limitation volontaire', None, None),
        ('alerte renforcée', 'Sensibilisation', 'Arrosage', 'Arrosage des pelouses, massifs fleuris', '', ' Limitation volontaire', None, None),
        ('alerte renforcée', 'Sensibilisation', 'Nettoyage', 'Lavage de véhicules chez les particuliers', '', ' Limitation volontaire', None, None),
        ('alerte renforcée', 'Sensibilisation', 'Remplissage vidange', "Remplissage et vidange de piscines privées (de plus d'1 m3)", '', 'Limitation volontaire', None, None),
        ('alerte renforcée', 'Sensibilisation', 'Travaux en cours d’eau', 'Travaux en cours d’eau', '', "Éviter de prévoir des travaux dont les interventions nécessitent le rejet d'effluents pas ou partiellement traités dans le milieu récepteur.", None, None),
        ('vigilance', 'Interdiction', 'Alimentation des fontaines publiques et privées', 'Alimentation des fontaines publiques et privées d’ornement', '', ' Interdit', None, None),
        ('vigilance', 'Interdiction', 'Alimentation des fontaines publiques et privées', 'Alimentation des fontaines publiques et privées d’ornement', '', " qui ne fonctionnent pas sur un circuit d'eau fermé", None, None),
        ('vigilance', 'Interdiction', 'Alimentation des fontaines publiques et privées', 'Alimentation des fontaines publiques et privées d’ornement', '', "qui ne fonctionnent pas sur un circuit d'eau fermé", None, None),
        ('vigilance', 'Interdiction', 'Arrosage', 'Arrosage des espaces verts', '', ' Interdit', None, None),
        ('vigilance', 'Interdiction', 'Arrosage', "Arrosage des golfs(Conformément à l'accord cadre golf et environnement 2019-2024", '', ' Interdit', None, None),
        ('vigilance', 'Interdiction', 'Arrosage', 'Arrosage des jardins potagers', '', ' Interdit', None, None),
        ('vigilance', 'Interdiction', 'Arrosage', 'Arrosage des pelouses, massifs fleuris', '', ' hors arrosage par micro-irrigation et goutte à goutte', None, None),
        ('vigilance', 'Interdiction', 'Arrosage', 'Arrosage des pelouses, massifs fleuris', '', ' Interdit', None, None),
        ('vigilance', 'Interdiction sauf exception', 'Arrosage', "Arrosage des golfs(Conformément à l'accord cadre golf et environnement 2019-2024", '', "A l'exception des greens et des départs", None, None),
        ('vigilance', 'Interdiction sauf exception', 'Arrosage', 'Arrosage des jardins potagers', '', 'les béals qui alimentent les jardins potagers sont soumis aux mêmes restrictions que les usages agricoles', None, None),
        ('vigilance', 'Interdiction sauf exception', 'Nettoyage', 'Lavage de véhicules chez les particuliers', '', ' Sauf pour les véhicules ayant une obligation réglementaire (véhicule sanitaire ou alimentaire) ou technique (épareuse, bétonnière,...) et pour les organismes liés à la sécurité.', None, None),
        ('vigilance', 'Interdiction sauf exception', 'Nettoyage', 'Lavage de véhicules chez les particuliers', '', 'Sauf pour les véhicules ayant une obligation réglementaire (véhicule sanitaire ou alimentaire) ou technique (épareuse, bétonnière, ...) et pour les organismes liés à la sécurité.', None, None),
        ('vigilance', 'Interdiction sauf exception', 'Remplissage vidange', "Remplissage et vidange de piscines privées (de plus d'1 m3)", '', "A l'exception de la première mise en eau des piscines nouvellement construites. A l'exception de la mise à niveau.", None, None),
        ('vigilance', 'Interdiction sauf exception', 'Remplissage vidange', "Remplissage et vidange de piscines privées (de plus d'1 m3)", '', 'Sauf la mise à niveau.', None, None),
        ('vigilance', 'Interdiction sauf exception', 'Travaux en cours d’eau', 'Travaux en cours d’eau', '', "Sauf autorisation service Police de l'Eau.", None, None),
        ('vigilance', 'Interdiction sur plage horaire', 'Arrosage', 'Arrosage des espaces verts', '', 'NULL', 8, 20),
        ('vigilance', 'Interdiction sur plage horaire', 'Arrosage', "Arrosage des golfs(Conformément à l'accord cadre golf et environnement 2019-2024", '', 'NULL', 8, 20),
        ('vigilance', 'Interdiction sur plage horaire', 'Arrosage', 'Arrosage des jardins potagers', '', 'NULL', 8, 10),
        ('vigilance', 'Interdiction sur plage horaire', 'Arrosage', 'Arrosage des jardins potagers', '', 'NULL', 10, 18),
        ('vigilance', 'Interdiction sur plage horaire', 'Arrosage', 'Arrosage des pelouses, massifs fleuris', '', 'NULL', 8, 20),
        ('vigilance', 'Pas de restriction', 'Abreuvement', 'Abreuvement des animaux', '', 'NULL', None, None),
        ('vigilance', 'Sensibilisation', 'Alimentation des fontaines publiques et privées', 'Alimentation des fontaines publiques et privées d’ornement', '', 'Limitation volontaire', None, None),
        ('vigilance', 'Sensibilisation', 'Arrosage', 'Arrosage des espaces verts', '', 'Limitation volontaire ', None, None),
        ('vigilance', 'Sensibilisation', 'Arrosage', "Arrosage des golfs(Conformément à l'accord cadre golf et environnement 2019-2024", '', ' Limitation volontaire', None, None),
        ('vigilance', 'Sensibilisation', 'Arrosage', 'Arrosage des jardins potagers', '', ' Limitation volontaire', None, None),
        ('vigilance', 'Sensibilisation', 'Arrosage', 'Arrosage des pelouses, massifs fleuris', '', ' Limitation volontaire', None, None),
        ('vigilance', 'Sensibilisation', 'Nettoyage', 'Lavage de véhicules chez les particuliers', '', ' Limitation volontaire', None, None),
        ('vigilance', 'Sensibilisation', 'Remplissage vidange', "Remplissage et vidange de piscines privées (de plus d'1 m3)", '', 'Limitation volontaire', None, None),
        ('vigilance', 'Sensibilisation', 'Travaux en cours d’eau', 'Travaux en cours d’eau', '', "Éviter de prévoir des travaux dont les interventions nécessitent le rejet d'effluents pas ou partiellement traités dans le milieu récepteur.", None, None)
    ]