services:
  pg:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: ecowater
      POSTGRES_USER: ecowater
      POSTGRES_DB: ecowater
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: ~
